### ISSUE TITLE
Provide an option to disable secured transport

### ISSUE THREAD

**Issue by Michsior14** [danielperna84/ha-philipsjs#23]
Even though TV respond with `"secured_transport": "true"`, any communication via `https` and port `1926` timeouts. It might be worth to provide the implicit option via config flow to use `http` only so the integration works in such case.

**Comment by elupus** [comment]
http does not work. Not all services are there. If https doesn't respond your tv has crashed.

**Comment by Michsior14** [comment]
Ahh, yes you are right. Looks like very first action done via HA (power on/ power off) crashes the https listeners (some http endpoints still work). Strange thing, because ha_`phillips_android_tv` worked before :/

**Comment by elupus** [comment]
Can you verify this? Is it really the first? Did you check that after a restart or how did you come to the conclusion it's the first?

**Comment by Michsior14** [comment]
Sorry for delay. I've just tested it a bit more deeply and I can confirm that it fails after the very first turn off action made from HA if the TV is displaying from HDMI. The test was pretty simple, hard restart of the tv (plug off the power), switch to HDMI and call turn off via HA.

~If the TV is displaying from it's own Android everything works perfectly fine (until change of source to HDMI).~
I was too fast with this statement, it just happened on build-in android as well after couple of volume changes.

Error from the failed action on the latest lib version (2.7.4) installed via `custom_components`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 231, in acquire
    await asyncio.wait_for(self.semaphore.acquire(), timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 277, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 225, in handle_async_request
    await self._add_to_pool(connection, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 360, in _add_to_pool
    await self._connection_semaphore.acquire(timeout=timeout.get("pool", None))
  File "/usr/local/lib/python3.8/site-packages/httpcore/_backends/asyncio.py", line 233, in acquire
    raise self.exc_class()
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/haphilipsjs/__init__.py", line 493, in getReq
    resp = await self.session.get(self._url(path))
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1662, in get
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1426, in request
    response = await self.send(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1511, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1546, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1580, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1621, in _send_single_request
    ) = await transport.handle_async_request(
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 272, in handle_async_request
    (
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 180, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/philips_js/__init__.py", line 159, in _async_update_data
    await self.api.update()
  File "/usr/local/lib/python3.8/site-packages/haphilipsjs/__init__.py", line 635, in update
    await self.getSystem()
  File "/usr/local/lib/python3.8/site-packages/haphilipsjs/__init__.py", line 671, in getSystem
    r = cast(Optional[SystemType], await self.getReq("system"))
  File "/usr/local/lib/python3.8/site-packages/haphilipsjs/__init__.py", line 506, in getReq
    raise GeneralFailure(err) from err
haphilipsjs.GeneralFailure
```
